# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
on:
  push:
    tags:
      - 'v*.*.*'
    
name: Release
  
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest

    runs-on: ${{ matrix.os }}
    env:
      TARGET: ${{ matrix.target }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Ensure Cargo.toml Version Matches Git Tag
        run: |
          toml_version=v$(sed -n 's/^version = "\(.*\)"/\1/p' < Cargo.toml)
          actual_version=$(git describe --tags --abbrev=0)
          if [[ "${toml_version}" != "${actual_version}" ]]; then
            echo "Refusing to publish - toml version doesn't match tag version"
            exit 1
          else
            echo "Git tag matches Cargo.toml)"
          fi

      - name: Cargo cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ./target
          key: build-cargo-registry-${{ matrix.target }}

      - name: Install Rust Target
        run: rustup target add ${{ matrix.target }}

      - name: Create Release Build 
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}
          path: ./target/release/topdrop

  deploy:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: result
          path: ./artifacts
      - name: List
        run: find ./artifacts
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./artifacts/*.tar.gz