# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
   
name: Release
  
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest

    runs-on: ${{ matrix.os }}
    env:
      TARGET: ${{ matrix.target }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Cargo cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ./target
          key: build-cargo-registry-${{ matrix.target }}

      - name: Install Rust Target
        run: rustup target add ${{ matrix.target }}

      - name: Create Release Build 
        run: |
          cargo build --release --target ${{ matrix.target }}
          ls target/

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}
          path: ./target/${{ matrix.target }}/release/topdrop
          if-no-files-found: error

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./artifacts

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./artifacts/*